{% set name = "pyknos" %}
{% set version = "0.16.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyknos-{{ version }}.tar.gz
  sha256: 4e1db834d8a5fd847882a081937732fea6798668b72293ae052765e7bfc371c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - nflows 0.14
    - numpy
    - tensorboard
    - pytorch
    - tqdm

test:
  imports:
    - pyknos
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sbi-dev/pyknos
  summary: don't regress. A package for neural conditional density estimation.
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/sbi-dev/pyknos

extra:
  recipe-maintainers:
    - matthewfeickert
